### ISSUE TITLE
Attempting to run in 0.25.9 gives me  "message": "service.initialize is not a function"

### ISSUE THREAD

**Issue by fourcolors** [fleek-platform/eliza-plugin-mcp#1]
Hey I'm running ElizaOS 0.25.9 with a config that looks like this:

<img width="697" alt="Image" src="https://github.com/user-attachments/assets/41d3f129-f911-448d-9248-7b4f573ac8ef" />

It's giving me this error: 

```
[2025-03-30 10:53:21] ERROR:
    err: {
      "type": "TypeError",
      "message": "service.initialize is not a function",
      "stack":
          TypeError: service.initialize is not a function
              at AgentRuntime.initialize (file:///----/eliza/packages/core/dist/index.js:4908:31)
              at startAgent (file:///----eliza/agent/src/index.ts:565:23)
              at async startAgents (file:///-----eliza/agent/src/index.ts:632:13)
    }

```

I think this is a bug?

**Comment by gabrielmpinto** [comment]
Hey @fourcolors, this plugin is actually for the upcoming Eliza v1, and was tested with Eliza >v1.0.0-beta.7

I did start work on a v0.25 version but considering Eliza v1 is coming out this week I stopped working on it

**Comment by tsubasakong** [comment]
curious about how you tested with Eliza >v1.0.0-beta.7 before this get merged into the registry?

**Comment by standujar** [comment]
Hi, are you working on the v1.0.0 ? I wanted to try that :)
